### ISSUE TITLE
Can't install V8

### ISSUE THREAD

**Issue by luigisison** [OCA/vertical-medical#107]
Get this error message when I attempt to Update Modules List in V8.

Odoo Server Error

---

Traceback (most recent call last):
  File "/odoo/odoo-server/openerp/http.py", line 539, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/openerp/http.py", line 576, in dispatch
    result = self._call_function(*_self.params)
  File "/odoo/odoo-server/openerp/http.py", line 312, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/odoo/odoo-server/openerp/service/model.py", line 118, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/odoo/odoo-server/openerp/http.py", line 309, in checked_call
    return self.endpoint(_a, *_kw)
  File "/odoo/odoo-server/openerp/http.py", line 805, in __call__
    return self.method(_args, *_kw)
  File "/odoo/odoo-server/openerp/http.py", line 405, in response_wrap
    response = f(_args, *_kw)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 1247, in load
    action = request.session.model(action_type).read([action_id], False, ctx)
  File "/odoo/odoo-server/openerp/http.py", line 910, in proxy
    result = meth(cr, request.uid, _args, *_kw)
  File "/odoo/odoo-server/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/odoo/odoo-server/openerp/addons/base/ir/ir_actions.py", line 326, in read
    results = super(ir_actions_act_window, self).read(cr, uid, ids, fields=fields, context=context, load=load)
  File "/odoo/odoo-server/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/odoo/odoo-server/openerp/models.py", line 3144, in read
    result = BaseModel.read(records, fields, load=load)
  File "/odoo/odoo-server/openerp/api.py", line 266, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/odoo/odoo-server/openerp/models.py", line 3179, in read
    self._read_from_database(stored, inherited)
  File "/odoo/odoo-server/openerp/api.py", line 266, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/odoo/odoo-server/openerp/models.py", line 3366, in _read_from_database
    res2 = self._columns[f].get(cr, self._model, ids, f, user, context=context, values=result)
  File "/odoo/odoo-server/openerp/osv/fields.py", line 1460, in get
    result = self._fnct(obj, cr, uid, ids, name, self._arg, context)
  File "/odoo/odoo-server/openerp/addons/base/ir/ir_actions.py", line 268, in _search_view
    'search', context=context)
  File "/odoo/odoo-server/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/odoo/odoo-server/openerp/models.py", line 1545, in fields_view_get
    xarch, xfields = View.postprocess_and_fields(cr, uid, self._name, etree.fromstring(result['arch']), view_id, context=ctx)
  File "/odoo/odoo-server/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/odoo/odoo-server/openerp/addons/base/ir/ir_ui_view.py", line 808, in postprocess_and_fields
    fields = Model.fields_get(cr, user, None, context=context)
  File "/odoo/odoo-server/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/odoo/odoo-server/openerp/models.py", line 3089, in fields_get
    description = field.get_description(recs.env)
  File "/odoo/odoo-server/openerp/fields.py", line 661, in get_description
    value = value(env)
  File "/odoo/odoo-server/openerp/fields.py", line 1393, in _description_selection
    return [(value, translate(label) if label else label) for value, label in selection]
  File "/odoo/odoo-server/openerp/api.py", line 266, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/odoo/odoo-server/openerp/api.py", line 487, in new_api
    result = method(self._model, cr, uid, _args, *_kwargs)
  File "/odoo/odoo-server/openerp/addons/base/ir/ir_translation.py", line 378, in _get_source
    return self.__get_source(cr, uid, name, types, lang, source, res_id)
  File "/odoo/odoo-server/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "<string>", line 2, in __get_source
  File "/odoo/odoo-server/openerp/tools/cache.py", line 74, in lookup
    value = d[key] = self.method(_args, *_kwargs)
  File "/odoo/odoo-server/openerp/addons/base/ir/ir_translation.py", line 345, in __get_source
    cr.execute(query, params)
  File "/odoo/odoo-server/openerp/sql_db.py", line 158, in wrapper
    return f(self, _args, *_kwargs)
  File "/odoo/odoo-server/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
InternalError: index "ir_translation_src_hash_idx" contains unexpected zero page at block 0
HINT:  Please REINDEX it.

**Comment by lasley** [comment]
Hi @luigisison - I don't see vertical medical in your traceback. What makes you believe that it is this repo causing the issue?

**Comment by lasley** [comment]
No response, closing
