### ISSUE TITLE
IntegrityError: insert or update on table "medical_appointment" violates foreign key constraint "medical_appointment_consultations_fkey"

### ISSUE THREAD

**Issue by askz** [OCA/vertical-medical#108]
Hi, I have a really annoying bug on medical module, when I install it the first time it's ok, I can inherit from it and create modules, update views and all, everything's fine.
But when there's data inputed (appointments, physicians) and I update medical module (with -u or update button in odoo) it's belzebut : 

```
2016-03-03 10:18:41,057 31738 DEBUG dev-cm openerp.models.schema: Table 'medical_appointment': added foreign key 'consultations' with definition=REFERENCES "medical_physician_services" ON DELETE set null
2016-03-03 10:18:41,196 31738 ERROR dev-cm openerp.sql_db: bad query: ALTER TABLE "medical_appointment" ADD FOREIGN KEY ("consultations") REFERENCES "medical_physician_services" ON DELETE set null
Traceback (most recent call last):
  File "/Users/akz/Projects/agile/dev/OCB/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
IntegrityError: insert or update on table "medical_appointment" violates foreign key constraint "medical_appointment_consultations_fkey"
DETAIL:  Key (consultations)=(2) is not present in table "medical_physician_services".

> /Users/akz/Projects/agile/dev/OCB/openerp/sql_db.py(234)execute()
-> res = self._obj.execute(query, params)
(Pdb) 2016-03-03 10:18:49,985 31738 DEBUG ? openerp.service.server: cron0 polling for jobs
2016-03-03 10:18:50,984 31738 DEBUG ? openerp.service.server: cron1 polling for jobs
c
2016-03-03 10:19:16,186 31738 ERROR dev-cm openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/Users/akz/Projects/agile/dev/OCB/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/Users/akz/Projects/agile/dev/OCB/openerp/http.py", line 574, in dispatch
    result = self._call_function(**self.params)
  File "/Users/akz/Projects/agile/dev/OCB/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/Users/akz/Projects/agile/dev/OCB/openerp/service/model.py", line 131, in wrapper
    registry = openerp.registry(dbname)
  File "/Users/akz/Projects/agile/dev/OCB/openerp/__init__.py", line 68, in registry
    return modules.registry.RegistryManager.get(database_name)
  File "/Users/akz/Projects/agile/dev/OCB/openerp/modules/registry.py", line 339, in get
    update_module)
  File "/Users/akz/Projects/agile/dev/OCB/openerp/modules/registry.py", line 370, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/Users/akz/Projects/agile/dev/OCB/openerp/modules/loading.py", line 351, in load_modules
    force, status, report, loaded_modules, update_module)
  File "/Users/akz/Projects/agile/dev/OCB/openerp/modules/loading.py", line 255, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/Users/akz/Projects/agile/dev/OCB/openerp/modules/loading.py", line 157, in load_module_graph
    init_module_models(cr, package.name, models)
  File "/Users/akz/Projects/agile/dev/OCB/openerp/modules/module.py", line 293, in init_module_models
    obj._auto_end(cr, {'module': module_name})
  File "/Users/akz/Projects/agile/dev/OCB/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/Users/akz/Projects/agile/dev/OCB/openerp/models.py", line 2711, in _auto_end
    cr.execute('ALTER TABLE "%s" ADD FOREIGN KEY ("%s") REFERENCES "%s" ON DELETE %s' % (t, k, r, d))
  File "/Users/akz/Projects/agile/dev/OCB/openerp/sql_db.py", line 158, in wrapper
    return f(self, *args, **kwargs)
  File "/Users/akz/Projects/agile/dev/OCB/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
IntegrityError: insert or update on table "medical_appointment" violates foreign key constraint "medical_appointment_consultations_fkey"
DETAIL:  Key (consultations)=(2) is not present in table "medical_physician_services".
```

I tried to figure out why but this get over me. Thanks for your time.

**Comment by lasley** [comment]
Hi @askz Thanks for the submission, sorry for the late reply. I've been trying to replicate this, have been able to reproduce a few times, but nothing consistent. Do you have a consistent way of reproducing this, with the specific modules installed at the time?

**Comment by askz** [comment]
Hi @lasley, in fact you just have to do some appointments, and restart odoo with -u medical
I just had the medical module installed. I'm currently working with this worktree : https://github.com/BusinessAgile/vertical-medical/tree/dev 
the medical_appointment_invoice module is progress, I have to refactor all this code.

**Comment by askz** [comment]
The branch has changed it's now https://github.com/BusinessAgile/vertical-medical/tree/8.0

**Comment by lasley** [comment]
@askz Have you made any progress on your branch? I will be upgrading `medical_appointment` here in the next week or two and want to make sure that effort isn't being duplicated.
