### ISSUE TITLE
Odoo v9 : Medical appointment

### ISSUE THREAD

**Issue by prihadi** [OCA/vertical-medical#116]
Hi Community,

Just installed the medical appointment module and got this error after selecting the appointment menu from Medical:

Odoo Server Error
Traceback (most recent call last):
  File "E:\Program Files\Odoo 9.0-20160729\server.\openerp\http.py", line 647, in _handle_exception
  File "E:\Program Files\Odoo 9.0-20160729\server.\openerp\http.py", line 684, in dispatch
  File "E:\Program Files\Odoo 9.0-20160729\server.\openerp\http.py", line 320, in _call_function
  File "E:\Program Files\Odoo 9.0-20160729\server.\openerp\service\model.py", line 118, in wrapper
  File "E:\Program Files\Odoo 9.0-20160729\server.\openerp\http.py", line 313, in checked_call
  File "E:\Program Files\Odoo 9.0-20160729\server.\openerp\http.py", line 963, in __call__
  File "E:\Program Files\Odoo 9.0-20160729\server.\openerp\http.py", line 513, in response_wrap
  File "E:\Program Files\Odoo 9.0-20160729\server\openerp\addons\web\controllers\main.py", line 897, in call_kw
  File "E:\Program Files\Odoo 9.0-20160729\server\openerp\addons\web\controllers\main.py", line 889, in _call_kw
  File "E:\Program Files\Odoo 9.0-20160729\server.\openerp\api.py", line 250, in wrapper
  File "E:\Program Files\Odoo 9.0-20160729\server.\openerp\models.py", line 2146, in read_group
  File "E:\Program Files\Odoo 9.0-20160729\server.\openerp\api.py", line 250, in wrapper
  File "E:\Program Files\Odoo 9.0-20160729\server.\openerp\models.py", line 1819, in _read_group_fill_results
TypeError: <lambda>() takes exactly 1 argument (8 given)

It's seems its not in the appointment modul itself.  Any clue for this error?

Thank you
Pri

**Comment by lasley** [comment]
Hi @prihadi - `medical-appointment` has not been converted to v9 & errors are expected. There is a WIP PR at #70 if you need the module, but it may not be compatible with the version that is released due to it being Work in progress.
