### ISSUE TITLE
when I try to install medical_prescription I get: KeyError: 'medical.prescription.order'

### ISSUE THREAD

**Issue by emanhaddad** [OCA/vertical-medical#118]
module: medical_prescription
version: 8.0.1.0

**Comment by lasley** [comment]
Thanks for the report @emanhaddad - can you please provide the full traceback?

**Comment by emanhaddad** [comment]
Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 8.0-20160823\server.\openerp\http.py", line 544, in _handle_exception
  File "C:\Program Files (x86)\Odoo 8.0-20160823\server.\openerp\http.py", line 581, in dispatch
  File "C:\Program Files (x86)\Odoo 8.0-20160823\server.\openerp\http.py", line 317, in _call_function
  File "C:\Program Files (x86)\Odoo 8.0-20160823\server.\openerp\service\model.py", line 118, in wrapper
  File "C:\Program Files (x86)\Odoo 8.0-20160823\server.\openerp\http.py", line 314, in checked_call
  File "C:\Program Files (x86)\Odoo 8.0-20160823\server.\openerp\http.py", line 810, in __call__
  File "C:\Program Files (x86)\Odoo 8.0-20160823\server.\openerp\http.py", line 410, in response_wrap
  File "C:\Program Files (x86)\Odoo 8.0-20160823\server\openerp\addons\web\controllers\main.py", line 948, in call_button
  File "C:\Program Files (x86)\Odoo 8.0-20160823\server\openerp\addons\web\controllers\main.py", line 936, in _call_kw
  File "C:\Program Files (x86)\Odoo 8.0-20160823\server.\openerp\api.py", line 268, in wrapper
  File "C:\Program Files (x86)\Odoo 8.0-20160823\server\openerp\addons\base\module\module.py", line 447, in button_immediate_install
  File "C:\Program Files (x86)\Odoo 8.0-20160823\server.\openerp\api.py", line 268, in wrapper
  File "C:\Program Files (x86)\Odoo 8.0-20160823\server\openerp\addons\base\module\module.py", line 495, in _button_immediate_function
  File "C:\Program Files (x86)\Odoo 8.0-20160823\server.\openerp\modules\registry.py", line 370, in new
  File "C:\Program Files (x86)\Odoo 8.0-20160823\server.\openerp\modules\loading.py", line 355, in load_modules
  File "C:\Program Files (x86)\Odoo 8.0-20160823\server.\openerp\modules\loading.py", line 255, in load_marked_modules
  File "C:\Program Files (x86)\Odoo 8.0-20160823\server.\openerp\modules\loading.py", line 152, in load_module_graph
  File "C:\Program Files (x86)\Odoo 8.0-20160823\server.\openerp\modules\registry.py", line 163, in load
  File "C:\Program Files (x86)\Odoo 8.0-20160823\server.\openerp\models.py", line 595, in _build_model
  File "C:\Program Files (x86)\Odoo 8.0-20160823\server.\openerp\modules\registry.py", line 102, in __getitem__
KeyError: 'medical.prescription.order'

**Comment by lasley** [comment]
@emanhaddad - I am unable to replicate this on my local or in Runbot. Your traceback seems to show inconsistent path hierarchy, so I think the issue lies in that:

Some are:

```
File "C:\Program Files (x86)\Odoo 8.0-20160823\server\*
```

But others are:

```
File "C:\Program Files (x86)\Odoo 8.0-20160823\server.\*
```

I recommend removing the `.` from the end of your server installation path and trying again. Please let me know if this fixes it.

**Comment by emanhaddad** [comment]
doesn't fix it

**Comment by lasley** [comment]
@emanhaddad - I'm still not able to replicate this unfortunately. I even double checked the model order in the init file (what normally causes this), and it is fine.

To rule out local issues, is this something you can also replicate on Runbot?

**Comment by lasley** [comment]
No response and likely local issue, closing. Please let us know if you still need assistance
