### ISSUE TITLE
Error in medical_insurance_company

### ISSUE THREAD

**Issue by mamaf** [OCA/vertical-medical#128]
When I try tocreate an "insurance provider", I get this error :

Traceback (most recent call last):
  File "/home/it-6it/aoe-dev_80/base/openerp/http.py", line 539, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/it-6it/aoe-dev_80/base/openerp/http.py", line 576, in dispatch
    result = self._call_function(**self.params)
  File "/home/it-6it/aoe-dev_80/base/openerp/http.py", line 312, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/it-6it/aoe-dev_80/base/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/it-6it/aoe-dev_80/base/openerp/http.py", line 309, in checked_call
    return self.endpoint(*a, **kw)
  File "/home/it-6it/aoe-dev_80/base/openerp/http.py", line 805, in __call__
    return self.method(*args, **kw)
  File "/home/it-6it/aoe-dev_80/base/openerp/http.py", line 405, in response_wrap
    response = f(*args, **kw)
  File "/home/it-6it/aoe-dev_80/base/addons/web/controllers/main.py", line 944, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/it-6it/aoe-dev_80/base/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/home/it-6it/aoe-dev_80/base/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/it-6it/aoe-dev_80/base/openerp/api.py", line 399, in old_api
    result = method(recs, *args, **kwargs)
  File "/home/it-6it/aoe-dev_80/base/openerp/models.py", line 5956, in onchange
    record._onchange_eval(name, field_onchange[name], result)
  File "/home/it-6it/aoe-dev_80/base/openerp/models.py", line 5861, in _onchange_eval
    method_res = getattr(self._model, method)(*args, context=self._context)
AttributeError: 'medical.insurance.company' object has no attribute 'onchange_address'

**Comment by lasley** [comment]
Hi @mamaf - thanks for the report. Fixed in #129 if you would like to review

**Comment by mamaf** [comment]
It's ok now

**Comment by lasley** [comment]
@mamaf Please also add an approval to the [Pull Request](https://github.com/OCA/vertical-medical/pull/129) if this fixed the issue. Thanks!
