### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by helenlisak** [OCA/vertical-medical#228]
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/tested/odoo/tools/convert.py", line 677, in _tag_root
    f(rec)
  File "/opt/tested/odoo/tools/convert.py", line 580, in _tag_record
    record = model._load_records([data], self.mode == 'update')
  File "/opt/tested/odoo/models.py", line 4186, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/opt/tested/odoo/models.py", line 4115, in _load_records_create
    return self.create(values)
  File "<decorator-gen-104>", line 2, in create
  File "/opt/tested/odoo/api.py", line 326, in _model_create_single
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/opt/tested/odoo/api.py", line 326, in <genexpr>
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/opt/tested/odoo/addons/base/models/res_users.py", line 1124, in create
    self._update_user_groups_view()
  File "/opt/tested/odoo/addons/base/models/res_users.py", line 1244, in _update_user_groups_view
    view.with_context(new_context).write({'arch': xml_content})
  File "/opt/tested/addons/website/models/theme_models.py", line 267, in write
    res = super(IrUiView, other_views).write(vals)
  File "/opt/tested/addons/website/models/ir_ui_view.py", line 68, in write
    return super(View, self).write(vals)
  File "/opt/tested/odoo/addons/base/models/ir_ui_view.py", line 500, in write
    res = super(View, self).write(self._compute_defaults(vals))
  File "/opt/tested/odoo/models.py", line 3670, in write
    fields[0].determine_inverse(real_recs)
  File "/opt/tested/odoo/fields.py", line 1147, in determine_inverse
    getattr(records, self.inverse)()
  File "/opt/tested/odoo/addons/base/models/ir_ui_view.py", line 300, in _inverse_arch
    view.write(data)
  File "/opt/tested/addons/website/models/theme_models.py", line 267, in write
    res = super(IrUiView, other_views).write(vals)
  File "/opt/tested/addons/website/models/ir_ui_view.py", line 68, in write
    return super(View, self).write(vals)
  File "/opt/tested/odoo/addons/base/models/ir_ui_view.py", line 500, in write
    res = super(View, self).write(self._compute_defaults(vals))
  File "/opt/tested/odoo/models.py", line 3665, in write
    real_recs._validate_fields(set(vals) - set(inverse_fields))
  File "/opt/tested/odoo/models.py", line 1250, in _validate_fields
    check(self)
  File "/opt/tested/odoo/addons/base/models/ir_ui_view.py", line 408, in _check_xml
    raise ValidationError(_(
  File "/opt/tested/odoo/addons/base/models/ir_ui_view.py", line 391, in _check_xml
    view.postprocess_and_fields(view_doc, validate=True)
  File "/opt/tested/odoo/addons/base/models/ir_ui_view.py", line 851, in postprocess_and_fields
    arch, name_manager = self._postprocess_view(node, model, validate=validate)
  File "/opt/tested/odoo/addons/base/models/ir_ui_view.py", line 862, in _postprocess_view
    name_manager = NameManager(validate, self.env[model])
  File "/opt/tested/odoo/addons/base/models/ir_ui_view.py", line 1930, in __init__
    self.fields_get = self.Model.fields_get()
  File "/opt/tested/odoo/addons/base/models/res_users.py", line 1441, in fields_get
    res = super(UsersView, self).fields_get(allfields, attributes=attributes)
  File "/opt/tested/odoo/models.py", line 2885, in fields_get
    description = field.get_description(self.env)
  File "/opt/tested/odoo/fields.py", line 665, in get_description
    value = value(env)
  File "/opt/tested/odoo/fields.py", line 2493, in _description_domain
    return self.domain(env[self.model_name]) if callable(self.domain) else self.domain
  File "/opt/tested/odoo/fields.py", line 2466, in <lambda>
    return lambda recs: self.domain(recs.env[self.model_name])
  File "/opt/tested/addons/medical/medical/models/res_partner.py", line 43, in <lambda>
    self.env.ref('product.product_uom_categ_kgm').id)
  File "/opt/tested/odoo/api.py", line 511, in ref
    return self['ir.model.data'].xmlid_to_object(xml_id, raise_if_not_found=raise_if_not_found)
  File "/opt/tested/odoo/addons/base/models/ir_model.py", line 1901, in xmlid_to_object
    t = self.xmlid_to_res_model_res_id(xmlid, raise_if_not_found)
  File "/opt/tested/odoo/addons/base/models/ir_model.py", line 1885, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(xmlid)[1:3]
  File "<decorator-gen-35>", line 2, in xmlid_lookup
  File "/opt/tested/odoo/tools/cache.py", line 90, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/opt/tested/odoo/addons/base/models/ir_model.py", line 1878, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
odoo.exceptions.ValidationError: Error while validating view:

External ID not found in the system: product.product_uom_categ_kgm

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/tested/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/opt/tested/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/opt/tested/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/tested/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/tested/odoo/http.py", line 347, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/tested/odoo/http.py", line 912, in __call__
    return self.method(*args, **kw)
  File "/opt/tested/odoo/http.py", line 531, in response_wrap
    response = f(*args, **kw)
  File "/opt/tested/addons/web/controllers/main.py", line 1381, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/opt/tested/addons/web/controllers/main.py", line 1369, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/tested/odoo/api.py", line 396, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/tested/odoo/api.py", line 383, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-71>", line 2, in button_immediate_install
  File "/opt/tested/odoo/addons/base/models/ir_module.py", line 73, in check_and_log
    return method(self, *args, **kwargs)
  File "/opt/tested/odoo/addons/base/models/ir_module.py", line 474, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/opt/tested/odoo/addons/base/models/ir_module.py", line 592, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/opt/tested/odoo/modules/registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/tested/odoo/modules/loading.py", line 453, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/opt/tested/odoo/modules/loading.py", line 346, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/opt/tested/odoo/modules/loading.py", line 221, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package)
  File "/opt/tested/odoo/modules/loading.py", line 69, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind)
  File "/opt/tested/odoo/tools/convert.py", line 733, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate)
  File "/opt/tested/odoo/tools/convert.py", line 799, in convert_xml_import
    obj.parse(doc.getroot())
  File "/opt/tested/odoo/tools/convert.py", line 719, in parse
    self._tag_root(de)
  File "/opt/tested/odoo/tools/convert.py", line 681, in _tag_root
    raise ParseError('while parsing %s:%s, near\n%s' % (
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/tested/odoo/http.py", line 639, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/tested/odoo/http.py", line 315, in _handle_exception
    raise exception.with_traceback(None) from new_cause
odoo.tools.convert.ParseError: while parsing /opt/tested/addons/medical/medical/security/medical_security.xml:9, near
<record id="group_medical_user" model="res.groups">
        <field name="name">User</field>
        <field name="category_id" ref="ir_module_category_medical"/>
        <field name="users" eval="[(4, ref('base.user_root'))]"/>
        <field name="implied_ids" eval="[(4, ref('base.group_user'))]"/>
    </record>

kindly help, this started after I installed partner_contact_weight

**Comment by helenlisak** [comment]
sorry, I couldn't even install that module, its installation is what is causing all the errors, what do I do?

**Comment by etobella** [comment]
Which version are you using?
