### ISSUE TITLE
Medical error when install on Odoo 14.0

### ISSUE THREAD

**Issue by vantinhuynh** [OCA/vertical-medical#230]
Hi team,

I got an issue when I install Medical module on Odoo 14.0
The error is:

`Error:
Odoo Server Error

Traceback (most recent call last):
  File "/Users/tinhuynh/Work/private_repo/odoo/odoo/tools/convert.py", line 677, in _tag_root
    f(rec)
  File "/Users/tinhuynh/Work/private_repo/odoo/odoo/tools/convert.py", line 580, in _tag_record
    record = model._load_records([data], self.mode == 'update')
  File "/Users/tinhuynh/Work/private_repo/odoo/odoo/models.py", line 4211, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/Users/tinhuynh/Work/private_repo/odoo/odoo/models.py", line 4140, in _load_records_create
    return self.create(values)
  File "<decorator-gen-42>", line 2, in create
  File "/Users/tinhuynh/Work/private_repo/odoo/odoo/api.py", line 345, in _model_create_multi
    return create(self, arg)
  File "/Users/tinhuynh/Work/private_repo/odoo/odoo/addons/base/models/ir_ui_view.py", line 482, in create
    return super(View, self).create(vals_list)
  File "<decorator-gen-64>", line 2, in create
  File "/Users/tinhuynh/Work/private_repo/odoo/odoo/api.py", line 345, in _model_create_multi
    return create(self, arg)
  File "/Users/tinhuynh/Work/private_repo/odoo/odoo/addons/base/models/ir_fields.py", line 533, in create
    recs = super().create(vals_list)
  File "<decorator-gen-13>", line 2, in create
  File "/Users/tinhuynh/Work/private_repo/odoo/odoo/api.py", line 345, in _model_create_multi
    return create(self, arg)
  File "/Users/tinhuynh/Work/private_repo/odoo/odoo/models.py", line 3901, in create
    fields[0].determine_inverse(batch_recs)
  File "/Users/tinhuynh/Work/private_repo/odoo/odoo/fields.py", line 1185, in determine_inverse
    getattr(records, self.inverse)()
  File "/Users/tinhuynh/Work/private_repo/odoo/odoo/addons/base/models/ir_ui_view.py", line 300, in _inverse_arch
    view.write(data)
  File "/Users/tinhuynh/Work/private_repo/odoo/odoo/addons/base/models/ir_ui_view.py", line 500, in write
    res = super(View, self).write(self._compute_defaults(vals))
  File "/Users/tinhuynh/Work/private_repo/odoo/odoo/models.py", line 3685, in write
    real_recs._validate_fields(vals, inverse_fields)
  File "/Users/tinhuynh/Work/private_repo/odoo/odoo/models.py", line 1260, in _validate_fields
    check(self)
  File "/Users/tinhuynh/Work/private_repo/odoo/odoo/addons/base/models/ir_ui_view.py", line 408, in _check_xml
    raise ValidationError(_(
  File "/Users/tinhuynh/Work/private_repo/odoo/odoo/addons/base/models/ir_ui_view.py", line 385, in _check_xml
    view_def = view.read_combined(['arch'])
  File "/Users/tinhuynh/Work/private_repo/odoo/odoo/addons/base/models/ir_ui_view.py", line 809, in read_combined
    arch = root.apply_view_inheritance(arch_tree, self.model)
  File "/Users/tinhuynh/Work/private_repo/odoo/odoo/addons/base/models/ir_ui_view.py", line 750, in apply_view_inheritance
    return self._apply_view_inheritance(source, inherit_tree)
  File "/Users/tinhuynh/Work/private_repo/odoo/odoo/addons/base/models/ir_ui_view.py", line 758, in _apply_view_inheritance
    source = view.apply_inheritance_specs(source, arch_tree)
  File "/Users/tinhuynh/Work/private_repo/odoo/odoo/addons/base/models/ir_ui_view.py", line 735, in apply_inheritance_specs
    self.handle_view_error(str(e))
  File "/Users/tinhuynh/Work/private_repo/odoo/odoo/addons/base/models/ir_ui_view.py", line 673, in handle_view_error
    raise ValueError(formatted_message).with_traceback(from_traceback) from from_exception
odoo.exceptions.ValidationError: Error while validating view:

Element '<xpath expr="//field[@name='translatable']">' cannot be located in parent view

View name: Res Lang Form - Default UoMs
Error context:
 view: ir.ui.view(440,)
 xmlid: res_lang_form
 view.model: res.lang
 view.parent: ir.ui.view(111,)
 file: /Users/tinhuynh/Work/private_repo/odoo/oca/server-tools/base_locale_uom_default/views/res_lang_view.xml

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/tinhuynh/Work/private_repo/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/Users/tinhuynh/Work/private_repo/odoo/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/Users/tinhuynh/Work/private_repo/odoo/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/Users/tinhuynh/Work/private_repo/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/Users/tinhuynh/Work/private_repo/odoo/odoo/http.py", line 347, in checked_call
    result = self.endpoint(*a, **kw)
  File "/Users/tinhuynh/Work/private_repo/odoo/odoo/http.py", line 912, in __call__
    return self.method(*args, **kw)
  File "/Users/tinhuynh/Work/private_repo/odoo/odoo/http.py", line 531, in response_wrap
    response = f(*args, **kw)
  File "/Users/tinhuynh/Work/private_repo/odoo/addons/web/controllers/main.py", line 1393, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/Users/tinhuynh/Work/private_repo/odoo/addons/web/controllers/main.py", line 1381, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/Users/tinhuynh/Work/private_repo/odoo/odoo/api.py", line 396, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/Users/tinhuynh/Work/private_repo/odoo/odoo/api.py", line 383, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-71>", line 2, in button_immediate_install
  File "/Users/tinhuynh/Work/private_repo/odoo/odoo/addons/base/models/ir_module.py", line 73, in check_and_log
    return method(self, *args, **kwargs)
  File "/Users/tinhuynh/Work/private_repo/odoo/odoo/addons/base/models/ir_module.py", line 474, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/Users/tinhuynh/Work/private_repo/odoo/odoo/addons/base/models/ir_module.py", line 592, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/Users/tinhuynh/Work/private_repo/odoo/odoo/modules/registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/Users/tinhuynh/Work/private_repo/odoo/odoo/modules/loading.py", line 453, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/Users/tinhuynh/Work/private_repo/odoo/odoo/modules/loading.py", line 346, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/Users/tinhuynh/Work/private_repo/odoo/odoo/modules/loading.py", line 221, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package)
  File "/Users/tinhuynh/Work/private_repo/odoo/odoo/modules/loading.py", line 69, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind)
  File "/Users/tinhuynh/Work/private_repo/odoo/odoo/tools/convert.py", line 733, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate)
  File "/Users/tinhuynh/Work/private_repo/odoo/odoo/tools/convert.py", line 799, in convert_xml_import
    obj.parse(doc.getroot())
  File "/Users/tinhuynh/Work/private_repo/odoo/odoo/tools/convert.py", line 719, in parse
    self._tag_root(de)
  File "/Users/tinhuynh/Work/private_repo/odoo/odoo/tools/convert.py", line 681, in _tag_root
    raise ParseError('while parsing %s:%s, near\n%s' % (
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/tinhuynh/Work/private_repo/odoo/odoo/http.py", line 639, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/Users/tinhuynh/Work/private_repo/odoo/odoo/http.py", line 315, in _handle_exception
    raise exception.with_traceback(None) from new_cause
odoo.tools.convert.ParseError: while parsing /Users/tinhuynh/Work/private_repo/odoo/oca/server-tools/base_locale_uom_default/views/res_lang_view.xml:4, near
<record id="res_lang_form" model="ir.ui.view">
        <field name="name">Res Lang Form - Default UoMs</field>
        <field name="model">res.lang</field>
        <field name="inherit_id" ref="base.res_lang_form"/>
        <field name="arch" type="xml">
            <xpath expr="//field[@name='translatable']" position="after">
                <field name="default_uom_ids"/>
            </xpath>
        </field>
    </record>`

What is the suitable Odoo version for Medical module?

**Comment by pedrobaeza** [comment]
These modules are not migrated since long and they are in fact not maintained anymore, due to a DMCA complaint (which I don't agree, but for not having to fight against it).
