### ISSUE TITLE
Error installing oemedical_emr_data

### ISSUE THREAD

**Issue by mwithi** [OCA/vertical-medical#36]
After installing:
- oemedical
- oemedical_emr

I get this error installing oemedical_emr_data module:

```
openerp.tools.convert: Parse error in oemedical_emr_data/data/WHO_list_of_essential_medicines.xml:6: 
<record model="oemedical.medicament" id="meds_em1">
        <field name="name" search="[('name', '=', 'halothane')]"/>
        <field name="active_component">halothane</field>
        <field name="category" model="oemedical.medicament.category" ref="em_1_1_1"/>
        <field name="pregnancy_warning">True</field>
        <field name="pregnancy_category">C</field>
        <field name="notes">Inhalation</field>
    </record>
Traceback (most recent call last):
  File "C:\Users\Nanni\git\odoo\openerp\tools\convert.py", line 852, in parse
    self._tags[rec.tag](self.cr, rec, n)
  File "C:\Users\Nanni\git\odoo\openerp\tools\convert.py", line 788, in _tag_record
    assert f_model, 'Define an attribute model="..." in your .XML file !'
AssertionError: Define an attribute model="..." in your .XML file !
2015-09-05 16:36:18,704 5340 ERROR TOSA_DEBUG openerp.osv.osv: Uncaught exception
Traceback (most recent call last):
  File "C:\Users\Nanni\git\odoo\openerp\osv\osv.py", line 132, in wrapper
    return f(self, dbname, *args, **kwargs)
  File "C:\Users\Nanni\git\odoo\openerp\osv\osv.py", line 199, in execute
    res = self.execute_cr(cr, uid, obj, method, *args, **kw)
  File "C:\Users\Nanni\git\odoo\openerp\osv\osv.py", line 187, in execute_cr
    return getattr(object, method)(cr, uid, *args, **kw)
  File "C:\Users\Nanni\git\odoo\openerp\addons\base\module\module.py", line 426, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "C:\Users\Nanni\git\odoo\openerp\addons\base\module\module.py", line 473, in _button_immediate_function
    _, pool = pooler.restart_pool(cr.dbname, update_module=True)
  File "C:\Users\Nanni\git\odoo\openerp\pooler.py", line 39, in restart_pool
    registry = RegistryManager.new(db_name, force_demo, status, update_module)
  File "C:\Users\Nanni\git\odoo\openerp\modules\registry.py", line 233, in new
    openerp.modules.load_modules(registry.db, force_demo, status, update_module)
  File "C:\Users\Nanni\git\odoo\openerp\modules\loading.py", line 355, in load_modules
    loaded_modules, update_module)
  File "C:\Users\Nanni\git\odoo\openerp\modules\loading.py", line 256, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "C:\Users\Nanni\git\odoo\openerp\modules\loading.py", line 188, in load_module_graph
    load_data(module_name, idref, mode)
  File "C:\Users\Nanni\git\odoo\openerp\modules\loading.py", line 76, in <lambda>
    load_data = lambda *args: _load_data(cr, *args, kind='data')
  File "C:\Users\Nanni\git\odoo\openerp\modules\loading.py", line 124, in _load_data
    tools.convert_xml_import(cr, module_name, fp, idref, mode, noupdate, report)
  File "C:\Users\Nanni\git\odoo\openerp\tools\convert.py", line 959, in convert_xml_import
    obj.parse(doc.getroot())
  File "C:\Users\Nanni\git\odoo\openerp\tools\convert.py", line 852, in parse
    self._tags[rec.tag](self.cr, rec, n)
  File "C:\Users\Nanni\git\odoo\openerp\tools\convert.py", line 788, in _tag_record
    assert f_model, 'Define an attribute model="..." in your .XML file !'
AssertionError: Define an attribute model="..." in your .XML file !
2015-09-05 16:36:18,707 5340 ERROR TOSA_DEBUG openerp.netsvc: Define an attribute model="..." in your .XML file !
Traceback (most recent call last):
  File "C:\Users\Nanni\git\odoo\openerp\netsvc.py", line 300, in dispatch_rpc
    result = ExportService.getService(service_name).dispatch(method, params)
  File "C:\Users\Nanni\git\odoo\openerp\service\web_services.py", line 632, in dispatch
    res = fn(db, uid, *params)
  File "C:\Users\Nanni\git\odoo\openerp\osv\osv.py", line 190, in execute_kw
    return self.execute(db, uid, obj, method, *args, **kw or {})
  File "C:\Users\Nanni\git\odoo\openerp\osv\osv.py", line 132, in wrapper
    return f(self, dbname, *args, **kwargs)
  File "C:\Users\Nanni\git\odoo\openerp\osv\osv.py", line 199, in execute
    res = self.execute_cr(cr, uid, obj, method, *args, **kw)
  File "C:\Users\Nanni\git\odoo\openerp\osv\osv.py", line 187, in execute_cr
    return getattr(object, method)(cr, uid, *args, **kw)
  File "C:\Users\Nanni\git\odoo\openerp\addons\base\module\module.py", line 426, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "C:\Users\Nanni\git\odoo\openerp\addons\base\module\module.py", line 473, in _button_immediate_function
    _, pool = pooler.restart_pool(cr.dbname, update_module=True)
  File "C:\Users\Nanni\git\odoo\openerp\pooler.py", line 39, in restart_pool
    registry = RegistryManager.new(db_name, force_demo, status, update_module)
  File "C:\Users\Nanni\git\odoo\openerp\modules\registry.py", line 233, in new
    openerp.modules.load_modules(registry.db, force_demo, status, update_module)
  File "C:\Users\Nanni\git\odoo\openerp\modules\loading.py", line 355, in load_modules
    loaded_modules, update_module)
  File "C:\Users\Nanni\git\odoo\openerp\modules\loading.py", line 256, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "C:\Users\Nanni\git\odoo\openerp\modules\loading.py", line 188, in load_module_graph
    load_data(module_name, idref, mode)
  File "C:\Users\Nanni\git\odoo\openerp\modules\loading.py", line 76, in <lambda>
    load_data = lambda *args: _load_data(cr, *args, kind='data')
  File "C:\Users\Nanni\git\odoo\openerp\modules\loading.py", line 124, in _load_data
    tools.convert_xml_import(cr, module_name, fp, idref, mode, noupdate, report)
  File "C:\Users\Nanni\git\odoo\openerp\tools\convert.py", line 959, in convert_xml_import
    obj.parse(doc.getroot())
  File "C:\Users\Nanni\git\odoo\openerp\tools\convert.py", line 852, in parse
    self._tags[rec.tag](self.cr, rec, n)
  File "C:\Users\Nanni\git\odoo\openerp\tools\convert.py", line 788, in _tag_record
    assert f_model, 'Define an attribute model="..." in your .XML file !'
AssertionError: Define an attribute model="..." in your .XML file !
```

**Comment by lasley** [comment]
Hi @mwithi - What Odoo version are you using, and what branch of this repo?

**Comment by lasley** [comment]
This should be resolved with the current version. Please let us know, or close the ticket if resolved.
