### ISSUE TITLE
Appointment - Change state

### ISSUE THREAD

**Issue by mmendozadelsolar** [OCA/vertical-medical#55]
in runbot:  8.0-incubator

When you treu to change the appointment state, you get this error:

Traceback (most recent call last):
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3117067-8-0-incubator-0edf75/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3117067-8-0-incubator-0edf75/openerp/http.py", line 574, in dispatch
    result = self._call_function(*_self.params)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3117067-8-0-incubator-0edf75/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3117067-8-0-incubator-0edf75/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3117067-8-0-incubator-0edf75/openerp/http.py", line 307, in checked_call
    return self.endpoint(_a, *_kw)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3117067-8-0-incubator-0edf75/openerp/http.py", line 803, in __call__
    return self.method(_args, *_kw)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3117067-8-0-incubator-0edf75/openerp/http.py", line 403, in response_wrap
    response = f(_args, *_kw)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3117067-8-0-incubator-0edf75/openerp/addons/web/controllers/main.py", line 948, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3117067-8-0-incubator-0edf75/openerp/addons/web/controllers/main.py", line 940, in _call_kw
    return checked_call(request.db, _args, *_kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3117067-8-0-incubator-0edf75/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3117067-8-0-incubator-0edf75/openerp/addons/web/controllers/main.py", line 939, in checked_call
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3117067-8-0-incubator-0edf75/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3117067-8-0-incubator-0edf75/openerp/addons/medical/models/medical_appointment.py", line 243, in write
    lang_id)[0]
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3117067-8-0-incubator-0edf75/openerp/models.py", line 5617, in __getitem__
    return self._browse(self.env, (self._ids[key],))
IndexError: tuple index out of range

**Comment by lasley** [comment]
Hi @mmendozadelsolar 

Thanks for the issue report! 8.0-incubator has gone some major overhauls, and currently has a good amount of pull request open.

That said, I'm seeing a different error on my local dev version using the current dev head.

I'll take a look next time I'm in this module. Should be soon.

```
Traceback (most recent call last):
  File "/var/www/rx/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/var/www/rx/openerp/http.py", line 574, in dispatch
    result = self._call_function(**self.params)
  File "/var/www/rx/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/var/www/rx/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/var/www/rx/openerp/http.py", line 307, in checked_call
    return self.endpoint(*a, **kw)
  File "/var/www/rx/openerp/http.py", line 803, in __call__
    return self.method(*args, **kw)
  File "/var/www/rx/openerp/http.py", line 403, in response_wrap
    response = f(*args, **kw)
  File "/var/www/rx/addons/web/controllers/main.py", line 948, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/var/www/rx/addons/web/controllers/main.py", line 940, in _call_kw
    return checked_call(request.db, *args, **kwargs)
  File "/var/www/rx/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/var/www/rx/addons/web/controllers/main.py", line 939, in checked_call
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/var/www/rx/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/var/www/rx/addons/medical/models/medical_appointment.py", line 247, in write
    datetime.strptime(date_start, DEFAULT_SERVER_DATETIME_FORMAT),
TypeError: must be string, not bool
```

**Comment by lasley** [comment]
Ahh so my error was due to me not putting a date into the record (should probably be a required field, will handle that).

Regarding your error, I cannot replicate this on the 8.0-iuncubator RunBot, so maybe it's a data issue. Can you please elaborate on the data being added into the Appointment?

**Comment by mmendozadelsolar** [comment]
Hi @lasley, try in the list view, and then change the state like the img:

![appointment odoo](https://cloud.githubusercontent.com/assets/7729857/11260314/f1f2947a-8e37-11e5-9dae-d28aad3e7892.png)

**Comment by lasley** [comment]
Hi @mmendozadelsolar 

Interesting, I can't replicate that error on my local install.

The error seems like it might be Runbot related. I'm not exactly sure how to login to OCA Runbot other than the clicking in the repo (which is not the right branch), so I'm somewhat at a loss on that side of things to be honest :confounded: 

![screen shot 2015-11-20 at 11 18 51 am](https://cloud.githubusercontent.com/assets/7397578/11309394/7f2d906a-8f78-11e5-922c-72d70810ed2f.png)

**Comment by mmendozadelsolar** [comment]
Hi @lasley, here is the link:

https://runbot.odoo-community.org/runbot/repo/github-com-oca-vertical-medical-159

**Comment by lasley** [comment]
Thanks @mmendozadelsolar - I got there, and now I just realized I should probably try admin/admin login! Error replicated- I'll dig deeper sometime tonight

**Comment by lasley** [comment]
@mmendozadelsolar - This should be resolved with the current version. Please let us know, or close the ticket if resolved.

**Comment by pedrobaeza** [comment]
Closing as well.
